{% set name = "cressent" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # path: ..
  git_url: https://github.com/ricrocha82/cressent/archive/refs/tags/v{{ version }}.tar.gz

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv"
  entry_points:
    - cressent = cressent_core.cli:cli
  noarch: python

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=64.0.0
    - wheel
  run:
    - python >=3.10
    - mafft=7.525 #
    - trimal=1.5.0 #
    - iqtree=2.3.6 #
    - seqkit=2.9.0 
    - pytest=8.3.4
    - pandas=2.2.3
    - biopython=1.85
    - blast=2.16.0
    - r-base>=4.0
    - r-ape=5.8
    - r-dendextend=1.19.0
    - r-ggseqlogo=0.2
    - bioconductor-biostrings=2.74.0
    - bioconductor-decipher=3.2.0
    - r-ggplot2=3.5.1
    - r-tidytree=0.4.6
    - r-dplyr=1.1.4
    - r-tidyr=1.3.1
    - r-rlang=1.1.4
    - r-RColorBrewer=1.1.3
    - bioconductor-treeio=1.30.0
    - bioconductor-ggtree=3.14.0
    - bioconductor-ggtreeextra=1.16.0
    - viennarna
    - gffutils=0.13
    - scipy=1.15.2
    - matplotlib=3.10.0
    - seaborn=0.13.2
    - meme=5.5.7
    - click

test:
  imports:
    - cressent_core
  commands:
    - cressent --help
    - cressent build_tree --help
    - cressent align --help

about:
  home: https://github.com/ricrocha82/cressent
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A comprehensive toolkit for ssDNA virus analysis'
  description: |
    cressent is a tool for analyzing ssDNA viruses, providing modules for 
    sequence alignment, phylogenetic analysis, motif discovery, visualization and more.
  doc_url: https://github.com/ricrocha82/cressent
  dev_url: https://github.com/ricrocha82/cressent

extra:
  recipe-maintainers:
    - ricrocha82
    - mtisza1