{% set name = "cressent" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # git_url: https://github.com/ricrocha82/cressent/archive/refs/tags/v{{ version }}.tar.gz
  url: file:///fs/project/PAS1117/ricardo/cressent/dist/cressent-0.1.0.tar.gz # test the source locally installed
  # path: /fs/project/PAS1117/ricardo/cressent/  # Path to your source directory 
  # sha256: 523b10e1d77a2c2492827074706f2e0697a9aadd97fb1eebebf479fb463f3ec1

build:
  number: 0
  script: 
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
  entry_points:
    - cressent = cressent.cli:cli
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=64.0.0
    - wheel
  run:
    - python >=3.6
    - mafft >=7.5 #
    - trimal >=1.4 #
    - iqtree >=2.0 #
    - seqkit
    - pandas
    - biopython
    - blast >=2.10
    - r-base >=4.0
    - r-ape
    - r-dendextend >=1.10
    - r-ggseqlogo
    - bioconductor-biostrings >=2.74.0
    - bioconductor-decipher >=3.2.0
    - r-ggplot2
    - r-tidytree >=0.4.0
    - r-dplyr
    - r-tidyr
    - r-rlang
    - r-gggenes >=0.5
    - r-RColorBrewer >=1.0
    - bioconductor-treeio >=1.0
    - bioconductor-ggtree >=3.10
    - bioconductor-ggtreeextra >=1.10
    - viennarna
    - gffutils
    - scipy
    - matplotlib
    - seaborn
    - meme >=5.0
    - click

test:
  imports:
    - cressent
  commands:
    - cressent --help
    - cressent build_tree --help
    - cressent align --help

about:
  home: https://github.com/ricrocha82/cressent
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A comprehensive toolkit for ssDNA virus analysis'
  description: |
    cressent is a tool for analyzing ssDNA viruses, providing modules for 
    sequence alignment, phylogenetic analysis, motif discovery, visualization and more.
  doc_url: https://github.com/ricrocha82/cressent
  dev_url: https://github.com/ricrocha82/cressent

extra:
  recipe-maintainers:
    - ricrocha82
    - mtisza1